### ISSUE TITLE
Possibly no longer needed

### ISSUE THREAD

**Issue by medikoo** [ryanmurakami/serverless-apigwy-binary#13]
I think functionality of this plugin is already supported by Framework natively, as you can configure:

```yaml
functions:
  someFunction:
    events:
      - http:
          ....
          response:
            contentHandling: CONVERT_TO_BINARY
```

It was added with https://github.com/serverless/serverless/pull/6987 which was released with https://github.com/serverless/serverless/releases/tag/v1.59.0

If my understanding is correct it might  be nice to deprecate it with appropriate messages
