### ISSUE TITLE
Prevent binary conversion of all api routes

### ISSUE THREAD

**Issue by izakblom** [ryanmurakami/serverless-apigwy-binary#2]
I tried using this plugin to convert one serverless api response to binary, as follows:
```
get_object:
    handler: Storage/handler.get_object
    events:
      - http:
          path: get_object
          method: get
          cors: true
          contentHandling: CONVERT_TO_BINARY
```

and
```
plugins:
  - serverless-apigwy-binary
```

But now all api route requests are also converted to binary? Is there a workaround for this?
