### ISSUE TITLE
Response setting of function is overwritten

### ISSUE THREAD

**Issue by pronoun66** [ryanmurakami/serverless-apigwy-binary#6]
My setting is as following code. In fact, CONVERT_TO_BINARY is successfully setup in apiGateway but response's headers were missing

```
functionA:
  events:
    - http:
        method: get
        path: ***
        integration: lambda
        contentHandling: CONVERT_TO_BINARY
        response:
          headers:
            Content-Type: "'application/pdf'"
```
